apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices-app
  template:
    metadata:
      labels:
        app: microservices-app
    spec:
      containers:
        - name: microservices-container
          image: your-dockerhub-username/microservices-app:latest
          ports:
            - containerPort: 5000
